Json/Models/ErrorViewModel.cs
namespace Json.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Json/Models/Item.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace Json.Models
{
    public class Item
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int Id { get; set; }
        public int? ParentId { get; set; }
        public string Name { get; set; }
        public string? Value { get; set; }
        public List<Item>? Children { get; set; }
    }
}

Json/ViewModels/InputFileViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Json.ViewModels
{
    public class InputFileViewModel
    {
        public IFormFile File { get; set; }
    }
}

Json/Controllers/HomeController.cs
using Json.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Json.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Json/Controllers/JsonController.cs
using Json.Interfaces;
using Json.Models;
using Json.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Json.Controllers
{
    public class JsonController : Controller
    {
        private readonly IProcessingRepository _processingRepository;
        public JsonController(IProcessingRepository processingRepository)
        {
            _processingRepository = processingRepository;
        }
        public async Task<IActionResult> Index()
        {
            return View();
        }
        public IActionResult Upload()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Upload(InputFileViewModel inputFileViewModel)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "An error occured during the loading of the file.");
            }
            
            try
            {
                _processingRepository.DeleteAllData();
                _processingRepository.Save();
                var fileContent = _processingRepository.ReadJsonFile(inputFileViewModel.File);
                List<Item> items = JsonConvert.DeserializeObject<List<Item>>(fileContent);
                if (items == null)
                {
                    ModelState.AddModelError("", "Object is empty.");
                }
                foreach(var item in items)
                {
                    _processingRepository.AddItem(item);
                }
                _processingRepository.Save();
            } catch (Exception ex)
            {
                ModelState.AddModelError("","An error occured during the uploading of the file.");
                return View("Index");
            }
            return View("Index");
        }
        public List<Item> BuildHierarchy(List<Item> flatItems)
        {
            Dictionary<int, Item> itemDictionary = new Dictionary<int, Item>();


            foreach (var item in flatItems)
            {
                item.Children = new List<Item>();
                itemDictionary[item.Id] = item;
            }


            foreach (var item in flatItems)
            {
                if (item.ParentId.HasValue && itemDictionary.ContainsKey(item.ParentId.Value))
                {
                    var parent = itemDictionary[item.ParentId.Value];
                    parent.Children.Add(item);
                }
            }

            return flatItems.Where(item => !item.ParentId.HasValue).ToList();
        }
        [HttpGet]
        public async Task<IActionResult> GetHierarchyJson()
        {

            var flatItems = await _processingRepository.GetAllItemsAsync();
            var hierarchy = BuildHierarchy(flatItems);
           
            var jsonResult = new JsonResult(hierarchy)
            {
                SerializerSettings = new JsonSerializerOptions
                {
                    WriteIndented = true,
                    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull
                }
            };

            return jsonResult;
        }        
    }
}

Json/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Json Parcing</h1>
    <p>Перейдіть на вкладку Json, далі для вибирайте Upload & Process для завантаження Json файлу.</p>
    <p>Після завантаження вашого файлу ви можете переглянути ваші дані у вигляді ієрархічного дерева натиснувши Hierarchy Tree.</p>
</div>

Json/Views/Json/GetHierarchyJson.cshtml
@model List<Item>

<h1>Configuration Tree</h1>

<div id="configuration-tree"></div>

@section scripts {
    <script>
        var configData = @Html.Raw(Json.Serialize(Model));
        
        $(function () {
            $('#configuration-tree').jstree({
                'core': {
                    'data': configData
                }
            });
        });
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.2.1/jstree.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.2.1/themes/default/style.min.css" />
}

Json/Views/Json/Index.cshtml
@using Json.Models
@model IEnumerable<Item>

<section class="py-5 text-center container">
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="fw-light">Json Processing</h1>
            <p class="lead text-body-secondary">Press 'Upload & Process' to upload and save your json file. Press 'Hierarchy Tree' to see it's hierarchy tree.</p>
            <p>
                <a asp-area="" asp-controller="Json" asp-action="Upload" class="btn btn-primary my-2">Upload & Process</a>
                <a asp-area="" asp-controller="Json" asp-action="GetHierarchyJson" class="btn btn-secondary my-2">Hierarchy Tree</a>
            </p>
        </div>
    </div>
</section>

Json/Views/Json/Upload.cshtml
@using Json.ViewModels
@model InputFileViewModel

@Html.AntiForgeryToken()

<form method="post" asp-action="Upload" enctype="multipart/form-data" id="uploadForm">
    <div class="form-group">
        <label asp-for="File">File</label>
        <input asp-for="File" type="file" class="form-control" id="fileInput" placeholder="Image" required>
        <span asp-validation-for="File" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary" id="submitButton" disabled>Submit</button>
</form>

@section scripts {
    <script>
        $(document).ready(function () {
            $('#fileInput').change(function () {
                $('#submitButton').prop('disabled', !$(this).val());
            });
        });
    </script>
}

Json/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - JsonWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Json.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">JsonWebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">                       
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Json" asp-action="Index">Json</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Json
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>